apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-deployment
spec:
  replicas: {{ .Values.codeExecution.replicas }}
  selector:
    matchLabels:
      app: code-execution
  template:
    metadata:
      labels:
        app: code-execution
    spec:
      containers:
        - name: code-execution
          image: {{ .Values.codeExecution.image }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: {{ .Values.codeExecution.resources.cpu }}
              memory: {{ .Values.codeExecution.resources.memory }}
