apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-deployment
spec:
  replicas: {{ .Values.codeExecution.replicas }}
  selector:
    matchLabels:
      app: code-execution
  template:
    metadata:
      labels:
        app: code-execution
    spec:
      containers:
        - name: code-execution
          image: {{ .Values.codeExecution.image }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: {{ .Values.codeExecution.resources.cpu }}
              memory: {{ .Values.codeExecution.resources.memory }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: tmp-dir
              mountPath: /tmp
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: tmp-dir
          hostPath:
            path: /tmp
