apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-deployment
spec:
  replicas: 3 # Number of pods to run
  selector:
    matchLabels:
      app: code-execution
  template:
    metadata:
      labels:
        app: code-execution
    spec:
      containers:
        - name: code-execution
          image: jyotindersingh/compiler-server
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: tmp-dir
              mountPath: /tmp
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: tmp-dir
          hostPath:
            path: /tmp
