apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-deployment
spec:
  replicas: 1 # Number of pods.
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
        - name: coordinator
          image: jyotindersingh/compiler-coordinator
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
